/* =====================================================
   CATÁLOGO DE PRODUTOS — TULIPA LINGERIE
   23 produtos da coleção real (@tulipa__lingerie)
   ===================================================== */

const PRODUTOS = [
  {
    id: 1,
    nome: "Conjunto Paixão Carmim",
    categoria: "conjunto",
    cor: ["vermelho"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 169.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-01.jpg",
    galeria: ["assets/img/produtos/produto-01.jpg", "assets/img/produtos/produto-01-02.jpg", "assets/img/produtos/produto-01-03.jpg", "assets/img/produtos/produto-01-04.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7Bio-ARH6/",
    descricao: "Conjunto em renda vermelha com detalhes em pedrarias coração — sedução pura para noites inesquecíveis.",
    composicao: "85% Poliamida · 15% Elastano. Renda francesa importada.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: true,
    novo: true
  },
  {
    id: 2,
    nome: "Tanga Pureza Marfim",
    categoria: "calcinha",
    cor: ["branco"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 59.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-02.jpg",
    galeria: ["assets/img/produtos/produto-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7BOYEASRH/",
    descricao: "Tanga em renda delicada cor marfim sobre cetim — clássico e atemporal.",
    composicao: "88% Poliamida · 12% Elastano. Renda marfim delicada.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 3,
    nome: "Tanga Veludo Borgonha",
    categoria: "calcinha",
    cor: ["bordo"],
    tamanhos: ["P", "M", "G"],
    preco: 69.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-03.jpg",
    galeria: ["assets/img/produtos/produto-03.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7BAWTAX8j/",
    descricao: "Renda bordô profunda em modelagem fio dental — luxo discreto.",
    composicao: "85% Poliamida · 15% Elastano. Veludo e renda bordô.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 4,
    nome: "Conjunto Cereja",
    categoria: "conjunto",
    cor: ["vermelho"],
    tamanhos: ["P", "M", "G"],
    preco: 189.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-04.jpg",
    galeria: ["assets/img/produtos/produto-04.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7AzzggQFo/",
    descricao: "Top corselet em renda vermelha vibrante com tanga combinando — para quem ousa.",
    composicao: "82% Poliamida · 18% Elastano. Renda francesa vermelha.",
    cuidados: "Lavar à mão em água fria. Não centrifugar. Secar à sombra.",
    destaque: false,
    novo: true
  },
  {
    id: 5,
    nome: "Conjunto Rubi Romântico",
    categoria: "conjunto",
    cor: ["vermelho"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 159.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-05.jpg",
    galeria: ["assets/img/produtos/produto-05.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7AeEUgem-/",
    descricao: "Sutiã em V profundo e calcinha em renda floral — feminilidade absoluta.",
    composicao: "85% Poliamida · 15% Elastano. Renda floral vermelha.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 6,
    nome: "Conjunto Céu de Verão",
    categoria: "conjunto",
    cor: ["azul"],
    tamanhos: ["P", "M", "G"],
    preco: 179.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-06.jpg",
    galeria: ["assets/img/produtos/produto-06.jpg", "assets/img/produtos/produto-06-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO7AHUAAVwD/",
    descricao: "Conjunto em renda azul serenidade — leveza e frescor para o seu dia.",
    composicao: "88% Poliamida · 12% Elastano. Renda azul serenidade.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 7,
    nome: "Conjunto Lavanda Eterna",
    categoria: "conjunto",
    cor: ["lila"],
    tamanhos: ["PP", "P", "M"],
    preco: 169.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-07.jpg",
    galeria: ["assets/img/produtos/produto-07.jpg", "assets/img/produtos/produto-07-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO6_4XMAVwh/",
    descricao: "Renda lilás suave em modelagem clássica — delicadeza em forma de peça.",
    composicao: "85% Poliamida · 15% Elastano. Renda lilás importada.",
    cuidados: "Lavar à mão em água fria. Não usar secadora. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 8,
    nome: "Conjunto Noite Veludo",
    categoria: "conjunto",
    cor: ["preto"],
    tamanhos: ["P", "M", "G", "GG"],
    preco: 189.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-08.jpg",
    galeria: ["assets/img/produtos/produto-08.jpg", "assets/img/produtos/produto-08-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO6_bLXgeXg/",
    descricao: "Renda preta translúcida com bordados — o mistério em forma de lingerie.",
    composicao: "80% Poliamida · 20% Elastano. Renda preta com bordados.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: true,
    novo: false
  },
  {
    id: 9,
    nome: "Conjunto Pôr-do-Sol",
    categoria: "conjunto",
    cor: ["coral"],
    tamanhos: ["P", "M", "G"],
    preco: 169.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-09.jpg",
    galeria: ["assets/img/produtos/produto-09.jpg", "assets/img/produtos/produto-09-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO6_ISYASaR/",
    descricao: "Tons quentes de coral em renda fina — o calor que te abraça.",
    composicao: "85% Poliamida · 15% Elastano. Renda coral delicada.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 10,
    nome: "Sutiã Renda Marfim",
    categoria: "sutia",
    cor: ["branco"],
    tamanhos: ["P", "M", "G"],
    preco: 119.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-10.jpg",
    galeria: ["assets/img/produtos/produto-10.jpg", "assets/img/produtos/produto-10-02.jpg", "assets/img/produtos/produto-10-03.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/DO6-c1_Acg1/",
    descricao: "Sutiã em renda marfim com bojo leve — versatilidade que combina com tudo.",
    composicao: "88% Poliamida · 12% Elastano. Renda marfim com bojo removível.",
    cuidados: "Lavar à mão em água fria. Não usar secadora. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 11,
    nome: "Conjunto Romã Selvagem",
    categoria: "conjunto",
    cor: ["vermelho"],
    tamanhos: ["P", "M", "G"],
    preco: 179.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-11.jpg",
    galeria: ["assets/img/produtos/produto-11.jpg", "assets/img/produtos/produto-11-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIyRK0pLGB/",
    descricao: "Conjunto em vermelho intenso com transparências estratégicas.",
    composicao: "82% Poliamida · 18% Elastano. Renda vermelha com transparência.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 12,
    nome: "Tanga Brisa Pérola",
    categoria: "calcinha",
    cor: ["branco"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 54.90,
    parcelas: 2,
    img: "assets/img/produtos/produto-12.jpg",
    galeria: ["assets/img/produtos/produto-12.jpg", "assets/img/produtos/produto-12-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIwpqRJ4ar/",
    descricao: "Renda branca como pétala de orquídea — pura simplicidade.",
    composicao: "90% Poliamida · 10% Elastano. Renda branca pérola.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 13,
    nome: "Conjunto Bordeaux Profundo",
    categoria: "conjunto",
    cor: ["bordo"],
    tamanhos: ["P", "M", "G", "GG"],
    preco: 189.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-13.jpg",
    galeria: ["assets/img/produtos/produto-13.jpg", "assets/img/produtos/produto-13-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIumVcpQ_N/",
    descricao: "Bordô profundo em renda francesa — para a mulher que sabe seu poder.",
    composicao: "85% Poliamida · 15% Elastano. Renda francesa bordô.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: true,
    novo: false
  },
  {
    id: 14,
    nome: "Calcinha Carícia Negra",
    categoria: "calcinha",
    cor: ["preto"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 64.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-14.jpg",
    galeria: ["assets/img/produtos/produto-14.jpg", "assets/img/produtos/produto-14-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIt_0cJ_BJ/",
    descricao: "Calcinha em renda preta com elástico delicado na cintura — clássico noir.",
    composicao: "88% Poliamida · 12% Elastano. Renda preta com elástico acetinado.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 15,
    nome: "Conjunto Anjo de Renda",
    categoria: "conjunto",
    cor: ["branco"],
    tamanhos: ["PP", "P", "M", "G"],
    preco: 179.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-15.jpg",
    galeria: ["assets/img/produtos/produto-15.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIpCpOpKMs/",
    descricao: "Branco angelical em renda chantilly — pureza com um toque sedutor.",
    composicao: "85% Poliamida · 15% Elastano. Renda chantilly branca.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 16,
    nome: "Tanga Rosa Antigo",
    categoria: "calcinha",
    cor: ["nude"],
    tamanhos: ["P", "M", "G"],
    preco: 59.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-16.jpg",
    galeria: ["assets/img/produtos/produto-16.jpg", "assets/img/produtos/produto-16-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIhY-yphVy/",
    descricao: "Rosa antigo em renda vintage — romantismo nas pequenas peças.",
    composicao: "88% Poliamida · 12% Elastano. Renda rose vintage.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 17,
    nome: "Conjunto Veludo Vermelho",
    categoria: "conjunto",
    cor: ["vermelho"],
    tamanhos: ["P", "M", "G"],
    preco: 199.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-17.jpg",
    galeria: ["assets/img/produtos/produto-17.jpg", "assets/img/produtos/produto-17-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIfKrxpeGK/",
    descricao: "Veludo vermelho com renda — peça statement para datas especiais.",
    composicao: "75% Poliamida · 25% Elastano. Veludo e renda vermelha.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: true,
    novo: false
  },
  {
    id: 18,
    nome: "Sutiã Encanto Lilás",
    categoria: "sutia",
    cor: ["lila"],
    tamanhos: ["P", "M", "G"],
    preco: 109.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-18.jpg",
    galeria: ["assets/img/produtos/produto-18.jpg", "assets/img/produtos/produto-18-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIdRCCJmiT/",
    descricao: "Sutiã lilás com renda delicada — feminilidade em estado puro.",
    composicao: "88% Poliamida · 12% Elastano. Renda lilás com bojo acolchoado.",
    cuidados: "Lavar à mão em água fria. Não usar secadora. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 19,
    nome: "Conjunto Pétala de Rosa",
    categoria: "conjunto",
    cor: ["rosa"],
    tamanhos: ["PP", "P", "M"],
    preco: 169.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-19.jpg",
    galeria: ["assets/img/produtos/produto-19.jpg", "assets/img/produtos/produto-19-02.jpg", "assets/img/produtos/produto-19-03.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CpIcaJJgBEn/",
    descricao: "Rosa suave com bordados florais — a primavera vestida.",
    composicao: "85% Poliamida · 15% Elastano. Renda rosa com bordados.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 20,
    nome: "Conjunto Onda Marinha",
    categoria: "conjunto",
    cor: ["azul"],
    tamanhos: ["P", "M", "G"],
    preco: 169.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-20.jpg",
    galeria: ["assets/img/produtos/produto-20.jpg", "assets/img/produtos/produto-20-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CmuwWnDpLus/",
    descricao: "Azul oceano em renda fluida — frescor e elegância.",
    composicao: "85% Poliamida · 15% Elastano. Renda azul marinho.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 21,
    nome: "Conjunto Sussurro Negro",
    categoria: "conjunto",
    cor: ["preto"],
    tamanhos: ["P", "M", "G", "GG"],
    preco: 179.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-21.jpg",
    galeria: ["assets/img/produtos/produto-21.jpg", "assets/img/produtos/produto-21-02.jpg", "assets/img/produtos/produto-21-03.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/Cmus2YmJa8H/",
    descricao: "Renda preta translúcida com costas trabalhadas — o segredo mais bem guardado.",
    composicao: "80% Poliamida · 20% Elastano. Renda preta com costas abertas.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 22,
    nome: "Calcinha Tentação Vermelha",
    categoria: "calcinha",
    cor: ["vermelho"],
    tamanhos: ["P", "M", "G"],
    preco: 69.90,
    parcelas: 3,
    img: "assets/img/produtos/produto-22.jpg",
    galeria: ["assets/img/produtos/produto-22.jpg", "assets/img/produtos/produto-22-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CmunbsLpGls/",
    descricao: "Vermelho paixão em modelagem fio — pequena, mas inesquecível.",
    composicao: "88% Poliamida · 12% Elastano. Renda vermelha fio dental.",
    cuidados: "Lavar à mão em água fria. Não usar alvejante. Secar à sombra.",
    destaque: false,
    novo: false
  },
  {
    id: 23,
    nome: "Conjunto Aurora",
    categoria: "conjunto",
    cor: ["lila", "rosa"],
    tamanhos: ["P", "M", "G"],
    preco: 189.90,
    parcelas: 4,
    img: "assets/img/produtos/produto-23.jpg",
    galeria: ["assets/img/produtos/produto-23.jpg", "assets/img/produtos/produto-23-02.jpg"],
    instagram: "https://www.instagram.com/tulipa__lingerie/p/CmukuT0JrW8/",
    descricao: "Degradê lilás-rosa em renda francesa — peça única e poética.",
    composicao: "85% Poliamida · 15% Elastano. Renda francesa degradê.",
    cuidados: "Lavar à mão em água fria. Não torcer. Secar à sombra.",
    destaque: true,
    novo: true
  }
];

/* Mapa de gradientes para placeholder de imagem por cor */
const COR_GRADIENTES = {
  vermelho: ['#8B1520', '#C41E3A'],
  branco:   ['#E8D5CF', '#FAF7F2'],
  bordo:    ['#4A0A12', '#800020'],
  azul:     ['#1E3A5F', '#4A6FA5'],
  lila:     ['#5E3580', '#B39DDB'],
  coral:    ['#C4513A', '#E8856A'],
  nude:     ['#9A7060', '#D4A5A0'],
  rosa:     ['#A02060', '#F48FB1'],
  preto:    ['#1A1818', '#3D3535'],
};
